### ISSUE TITLE
The result of looping of all possible combination of "書く"

### ISSUE THREAD

**Issue by shilik** [fasiha/kamiya-codec#3]
Hi, @fasiha 

I used two arrays to loop through all combinations of "書く"
	auxiliary_con: [
				codec.Auxiliary.Masu,
				codec.Auxiliary.Nai,
				codec.Auxiliary.Tai,
				codec.Auxiliary.Tagaru,
				codec.Auxiliary.Hoshii,
				codec.Auxiliary.Rashii,
				codec.Auxiliary.SoudaHearsay,
				codec.Auxiliary.SoudaConjecture,
				codec.Auxiliary.SeruSaseru,
				codec.Auxiliary.ShortenedCausative,
				codec.Auxiliary.ReruRareu,
				codec.Auxiliary.CausativePassive,
				codec.Auxiliary.ShortenedCausativePassive
			],
			codec_con: [
				codec.Conjugation.Negative,
				codec.Conjugation.Conjunctive,
				codec.Conjugation.Dictionary,
				codec.Conjugation.Conditional,
				codec.Conjugation.Imperative,
				codec.Conjugation.Volitional,
				codec.Conjugation.Te,
				codec.Conjugation.Ta,
				codec.Conjugation.Tara,
				codec.Conjugation.Tari
			]

And here are the results:
it seems that some combinations yielded errors like  [Error: Unhandled conjugation]  and some combinations are ungrammatical.
It is OK with the errors as they are simply the results of impossible combinations.
But for the part of ungrammatical, Maybe some rules, especiall conditionalば,  need to be modified to solve these problems.

JS: 'Potential+Negative' [ '書きません', [length]: 1 ]
JS: 'Potential+ Conjunctive' [Error: Unhandled conjugation]
JS: 'Potential+Dictionary' [ '書きます', [length]: 1 ]
#ungrammatical
JS: 'Potential+Conditional' [ '書きますれば', [length]: 1 ]

JS: 'Potential+Imperative' [ '書きませ', [length]: 1 ]
JS: 'Potential+Volitional' [ '書きましょう', [length]: 1 ]
JS: 'Potential+Te' [ '書きまして', [length]: 1 ]
JS: 'Potential+Ta' [ '書きました', [length]: 1 ]
JS: 'Potential+Tara' [ '書きましたら', [length]: 1 ]
JS: 'Potential+ Tari' [Error: Unhandled conjugation]
JS: 'Masu+Negative' [ '書かなくはない', [length]: 1 ]
JS: 'Masu+Conjunctive' [ '書かなく', [length]: 1 ]
JS: 'Masu+Dictionary' [ '書かない', [length]: 1 ]
JS: 'Masu+Conditional' [ '書かなければ', [length]: 1 ]
JS: 'Masu+ Imperative' [Error: Unhandled conjugation]
JS: 'Masu+ Volitional' [Error: Unhandled conjugation]
JS: 'Masu+Te' [ '書かなくて', [length]: 1 ]
JS: 'Masu+Ta' [ '書かなかった', [length]: 1 ]
JS: 'Masu+Tara' [ '書かなかったら', [length]: 1 ]
JS: 'Masu+ Tari' [Error: Unhandled conjugation]
JS: 'Nai+Negative' [ '書きたくない', [length]: 1 ]
JS: 'Nai+Conjunctive' [ '書きたく', [length]: 1 ]
JS: 'Nai+Dictionary' [ '書きたい', [length]: 1 ]
JS: 'Nai+Conditional' [ '書きたければ', [length]: 1 ]
JS: 'Nai+ Imperative' [Error: Unhandled conjugation]
JS: 'Nai+ Volitional' [Error: Unhandled conjugation]
JS: 'Nai+Te' [ '書きたくて', [length]: 1 ]
JS: 'Nai+Ta' [ '書きたかった', [length]: 1 ]
JS: 'Nai+Tara' [ '書きたかったら', [length]: 1 ]
JS: 'Nai+ Tari' [Error: Unhandled conjugation]

#no  い
JS: 'Tai+Negative' [ '書きたがら', [length]: 1 ]

JS: 'Tai+Conjunctive' [ '書きたがり', [length]: 1 ]
JS: 'Tai+Dictionary' [ '書きたがる', [length]: 1 ]
JS: 'Tai+ Conditional' [Error: Unhandled conjugation]
JS: 'Tai+ Imperative' [Error: Unhandled conjugation]
JS: 'Tai+ Volitional' [Error: Unhandled conjugation]
JS: 'Tai+Te' [ '書きたがって', [length]: 1 ]
JS: 'Tai+Ta' [ '書きたがった', [length]: 1 ]
JS: 'Tai+Tara' [ '書きたがったら', [length]: 1 ]
JS: 'Tai+ Tari' [Error: Unhandled conjugation]
JS: 'Tagaru+Negative' [ '書いてほしくない', [length]: 1 ]
JS: 'Tagaru+Conjunctive' [ '書いてほしく', [length]: 1 ]
JS: 'Tagaru+Dictionary' [ '書いてほしい', [length]: 1 ]
JS: 'Tagaru+Conditional' [ '書いてほしければ', [length]: 1 ]
JS: 'Tagaru+ Imperative' [Error: Unhandled conjugation]
JS: 'Tagaru+ Volitional' [Error: Unhandled conjugation]
JS: 'Tagaru+Te' [ '書いてほしくて', [length]: 1 ]
JS: 'Tagaru+Ta' [ '書いてほしかった', [length]: 1 ]
JS: 'Tagaru+Tara' [ '書いてほしかったら', [length]: 1 ]
JS: 'Tagaru+ Tari' [Error: Unhandled conjugation]
JS: 'Hoshii+Negative' [ '書かないらしい', [length]: 1 ]
JS: 'Hoshii+Conjunctive' [ '書いたらしく', '書くらしく', [length]: 2 ]
JS: 'Hoshii+Dictionary' [ '書いたらしい', '書くらしい', [length]: 2 ]
JS: 'Hoshii+ Conditional' [Error: Unhandled conjugation]
JS: 'Hoshii+ Imperative' [Error: Unhandled conjugation]
JS: 'Hoshii+ Volitional' [Error: Unhandled conjugation]
JS: 'Hoshii+Te' [ '書いたらしくて', '書くらしくて', [length]: 2 ]
JS: 'Hoshii+ Ta' [Error: Unhandled conjugation]
JS: 'Hoshii+ Tara' [Error: Unhandled conjugation]
JS: 'Hoshii+ Tari' [Error: Unhandled conjugation]
JS: '書いた' '書く'
JS: 'Rashii+ Negative' [Error: Unhandled conjugation]
JS: '書いた' '書く'
JS: 'Rashii+ Conjunctive' [Error: Unhandled conjugation]
JS: '書いた' '書く'
JS: 'Rashii+Dictionary' [ '書いたそうだ', '書くそうだ', [length]: 2 ]
JS: '書いた' '書く'
JS: 'Rashii+ Conditional' [Error: Unhandled conjugation]
JS: '書いた' '書く'
JS: 'Rashii+ Imperative' [Error: Unhandled conjugation]
JS: '書いた' '書く'
JS: 'Rashii+ Volitional' [Error: Unhandled conjugation]
JS: '書いた' '書く'
JS: 'Rashii+ Te' [Error: Unhandled conjugation]
JS: '書いた' '書く'
JS: 'Rashii+ Ta' [Error: Unhandled conjugation]
JS: '書いた' '書く'
JS: 'Rashii+ Tara' [Error: Unhandled conjugation]
JS: '書いた' '書く'
JS: 'Rashii+ Tari' [Error: Unhandled conjugation]
JS: 'SoudaHearsay+ Negative' [Error: Unhandled conjugation]
JS: 'SoudaHearsay+ Conjunctive' [Error: Unhandled conjugation]
JS: 'SoudaHearsay+Dictionary' [ '書きそうだ', [length]: 1 ]
JS: 'SoudaHearsay+Conditional' [ '書きそうなら', [length]: 1 ]
JS: 'SoudaHearsay+ Imperative' [Error: Unhandled conjugation]
JS: 'SoudaHearsay+ Volitional' [Error: Unhandled conjugation]
JS: 'SoudaHearsay+ Te' [Error: Unhandled conjugation]
JS: 'SoudaHearsay+Ta' [ '書きそうだった', [length]: 1 ]
JS: 'SoudaHearsay+ Tara' [Error: Unhandled conjugation]
JS: 'SoudaHearsay+ Tari' [Error: Unhandled conjugation]
JS: 'SoudaConjecture+Negative' [ '書かせ', [length]: 1 ]
JS: 'SoudaConjecture+Conjunctive' [ '書かせ', [length]: 1 ]
JS: 'SoudaConjecture+Dictionary' [ '書かせる', [length]: 1 ]
#need  ば in the end
JS: 'SoudaConjecture+Conditional' [ '書かせれ', [length]: 1 ]
JS: 'SoudaConjecture+Imperative' [ '書かせろ', '書かせよ', [length]: 2 ]
JS: 'SoudaConjecture+Volitional' [ '書かせよう', [length]: 1 ]
JS: 'SoudaConjecture+Te' [ '書かせて', [length]: 1 ]
JS: 'SoudaConjecture+Ta' [ '書かせた', [length]: 1 ]
JS: 'SoudaConjecture+ Tara' [Error: Unhandled conjugation]
JS: 'SoudaConjecture+ Tari' [Error: Unhandled conjugation]
JS: 'SeruSaseru+Negative' [ '書かさ', [length]: 1 ]
JS: 'SeruSaseru+Conjunctive' [ '書かし', [length]: 1 ]
JS: 'SeruSaseru+Dictionary' [ '書かす', [length]: 1 ]

#need  ば in the end
JS: 'SeruSaseru+Conditional' [ '書かせ', [length]: 1 ]
JS: 'SeruSaseru+Imperative' [ '書かせ', [length]: 1 ]
JS: 'SeruSaseru+Volitional' [ '書かそ', [length]: 1 ]
JS: 'SeruSaseru+Te' [ '書かして', [length]: 1 ]

# sould be Ta not Da
JS: 'SeruSaseru+Ta' [ '書かしだ', [length]: 1 ]

JS: 'SeruSaseru+ Tara' [Error: Unhandled conjugation]
JS: 'SeruSaseru+ Tari' [Error: Unhandled conjugation]
JS: 'ShortenedCausative+Negative' [ '書かれ', [length]: 1 ]
JS: 'ShortenedCausative+Conjunctive' [ '書かれ', [length]: 1 ]
JS: 'ShortenedCausative+Dictionary' [ '書かれる', [length]: 1 ]
JS: 'ShortenedCausative+ Conditional' [Error: Unhandled conjugation]
JS: 'ShortenedCausative+ Imperative' [Error: Unhandled conjugation]
JS: 'ShortenedCausative+ Volitional' [Error: Unhandled conjugation]
JS: 'ShortenedCausative+Te' [ '書かれて', [length]: 1 ]
JS: 'ShortenedCausative+Ta' [ '書かれた', [length]: 1 ]
JS: 'ShortenedCausative+ Tara' [Error: Unhandled conjugation]
JS: 'ShortenedCausative+ Tari' [Error: Unhandled conjugation]
JS: 'ReruRareu+Negative' [ '書かせられ', [length]: 1 ]
JS: 'ReruRareu+Conjunctive' [ '書かせられ', [length]: 1 ]
JS: 'ReruRareu+Dictionary' [ '書かせられる', [length]: 1 ]
#need  ば in the end
JS: 'ReruRareu+Conditional' [ '書かせられれ', [length]: 1 ]

JS: 'ReruRareu+Imperative' [ '書かせられろ', '書かせられよ', [length]: 2 ]
JS: 'ReruRareu+Volitional' [ '書かせられよう', [length]: 1 ]
JS: 'ReruRareu+Te' [ '書かせられて', [length]: 1 ]
JS: 'ReruRareu+Ta' [ '書かせられた', [length]: 1 ]
JS: 'ReruRareu+Tara' [ '書かせられたら', [length]: 1 ]
JS: 'ReruRareu+Tari' [ '書かせられたり', [length]: 1 ]
JS: 'CausativePassive+Negative' [ '書かされ', [length]: 1 ]
JS: 'CausativePassive+Conjunctive' [ '書かされ', [length]: 1 ]
JS: 'CausativePassive+Dictionary' [ '書かされる', [length]: 1 ]
#need  ば in the end
JS: 'CausativePassive+Conditional' [ '書かされれ', [length]: 1 ]

JS: 'CausativePassive+Imperative' [ '書かされろ', '書かされよ', [length]: 2 ]
JS: 'CausativePassive+Volitional' [ '書かされよう', [length]: 1 ]
JS: 'CausativePassive+Te' [ '書かされて', [length]: 1 ]
JS: 'CausativePassive+Ta' [ '書かされた', [length]: 1 ]
JS: 'CausativePassive+Tara' [ '書かされたら', [length]: 1 ]
JS: 'CausativePassive+Tari' [ '書かされたり', [length]: 1 ]

**Comment by fasiha** [comment]
Thank you for this! This is the kind of close inspection that this package needed! Let me try and collect all the issues you mention into some groups:

## 1. だ instead of た?
書かしだ, that's wrong!!! But, is there maybe a small mistake in this, because for me, `codec.conjugateAuxiliary('書く', codec.Auxiliary.SeruSaseru, codec.Conjugation.Ta) // [ '書かせた' ]`? I ran the following code to loop over all auxiliaries and conjugations:
```js
var codec = require('./index');
var v = '書く';
for (var iaux = 0, aux = codec.Auxiliary[iaux]; aux = codec.Auxiliary[iaux]; iaux++) {
  for (var icon = 0, conj = codec.Conjugation[icon]; conj = codec.Conjugation[icon]; icon++) {
    var res = 'xxx';
    try {
      res = codec.conjugateAuxiliary(v, iaux, icon).join(' / ');
    } catch (e) {}
    console.log(aux, conj, res);
  }
}
```
And searching the output of this, I see that `ShortenedCausative Ta 書かしだ`. I had a copy-paste bug in my code, and I didn't test す+past tense, so it wasn't caught 😿, but now it is fixed and a test added 😄!

## 2. Missing ば
About the ば at the end of the conditional—these are left off because in the book, Kamiya-sensei indicates the ば in parentheses, which she does when the conjugation is often used with something but not always:

![kamiya](https://user-images.githubusercontent.com/37649/48680620-de185f00-eb6a-11e8-89ac-25f233f23920.jpg)

***But*** I checked all the examples of using the conditional in the book, and all of them have ば, sooo I'm ok with adding ば as a suffix when using `codec.Conjugation.Conditional`. This will take a bit more testing than I can do right now—I'm opening a branch for this and should have it done within 24 hours and will update this when that's done.

## 3. "no い"
My code snippet above produces `Tagaru Negative 書きたがら`, and

**Comment by shilik** [comment]
I have corrected some of the errors in the converted index.js.
Just for your reference, here are the corrected ones. 

const specialCasesRaw = [
	["ある", Conjugation.Negative, "ない"],
	["ござる", Conjugation.Conjunctive, "ござい"],
	["いらっしゃる", Conjugation.Conjunctive, "いらっしゃい"],
	["いらっしゃる", Conjugation.Conditional, "いらっしゃい"],
	["いらっしゃる", Conjugation.Imperative, "いらっしゃい"]
];

const tteRaw = [
	["く", ["いて", "いた", "いたら", "いたり"]],
	["ぐ", ["いで", "いだ", "いだら", "いだり"]],
	["す", ["して", "した", "したら", "したり"]],
	["ぬ", ["んで", "んだ", "んだら", "んだり"]],
	["ぶ", ["んで", "んだ", "んだら", "んだり"]],
	["む", ["んで", "んだ", "んだら", "んだり"]],
	["つ", ["って", "った", "ったら", "ったり"]],
	["る", ["って", "った", "ったら", "ったり"]],
	["う", ["って", "った", "ったら", "ったり"]]
];

function conjugateTypeII(verb, conj) {
	if (verb === "する") {
		return conjugateSuru(verb, conj);
	} else if (verb === "くる" || verb === "来る") {
		return conjugateKuru(verb, conj);
	}
	const head = verb.slice(0, -1);
	switch (conj) {
		case Conjugation.Negative:
			return [head];
		case Conjugation.Conjunctive:
			return [head];
		case Conjugation.Dictionary:
			return [verb];
		case Conjugation.Conditional:
			return [head + "れば"];
		case Conjugation.Imperative:
			return [head + "ろ", head + "よ"];
		case Conjugation.Volitional:
			return [head + "よう"];
		case Conjugation.Te:
			return [head + "て"];
		case Conjugation.Ta:
			return [head + "た"];
		case Conjugation.Tara:
			return [head + "たら"];
		case Conjugation.Tari:
			return [head + "たり"];
		default:
			throw new Error("Unhandled conjugation");
	}
}

function conjugateKuru(verb, conj) {
	let ret = "";
	switch (conj) {
		case Conjugation.Negative:
			ret = "こ";
			break;
		case Conjugation.Conjunctive:
			ret = "き";
			break;
		case Conjugation.Dictionary:
			ret = "くる";
			break;
		case Conjugation.Conditional:
			ret = "くれば";
			break;
		case Conjugation.Imperative:
			ret = "こい";
			break;
		case Conjugation.Volitional:
			ret = "こよう";
			break;
		case Conjugation.Te:
			ret = "きて";
			break;
		case Conjugation.Ta:
			ret = "きた";
			break;
		case Conjugation.Tara:
			ret = "きたら";
			break;
		case Conjugation.Tari:
			ret = "きたり";
			break;
		default:
			throw new Error("Unhandled conjugation");
	}
function conjugateAuxiliary(verb, aux, conj, typeII = false) {
	if (aux === Auxiliary.Potential) {
		const newverb = conjugateTypeI(verb, Conjugation.Conditional)[0] + "る";
		return conjugateTypeII(newverb, conj);
	} else if (aux === Auxiliary.Masu) {
		const base = conjugate(verb, Conjugation.Conjunctive, typeII);
		switch (conj) {
			case Conjugation.Negative:
				return [base + "ません"];
			// case Conjugation.Conjunctive:
			case Conjugation.Dictionary:
				return [base + "ます"];
			case Conjugation.Conditional:
				return [base + "れば"];
			case Conjugation.Imperative:
				return [base + "ませ"];
			case Conjugation.Volitional:
				return [base + "ましょう"];
			case Conjugation.Te:
				return [base + "まして"];
			case Conjugation.Ta:
				return [base + "ました"];
			case Conjugation.Tara:
				return [base + "ましたら"];
			// case Conjugation.Tari:
			default:
				throw new Error("Unhandled conjugation");
		}
..........

**Comment by shilik** [comment]
I noticed that you didn't deal with the special case of conditional in type I, It is OK for type II verbs as it will turn out to be 食べ＋れば, but for type I verb, we need to know what kind of tail a verb has in order to make a conditional form. i.e.ある＝＞る＝＞あれば　書く＝＞く＝＞書けば

**Comment by shilik** [comment]
> 
> 
> Thank you for this! This is the kind of close inspection that this package needed! Let me try and collect all the issues you mention into some groups:
> ## 1. だ instead of た?
> 
> 書かしだ, you are totally right, that's wrong!!! But, is there maybe a small mistake in the list of conjugations you produced, because for me, `codec.conjugateAuxiliary('書く', codec.Auxiliary.SeruSaseru, codec.Conjugation.Ta) // [ '書かせた' ]`? I ran the following code to loop over all auxiliaries and conjugations:
> 
> ```js
> var codec = require('./index');
> var v = '書く';
> for (var iaux = 0, aux = codec.Auxiliary[iaux]; aux = codec.Auxiliary[iaux]; iaux++) {
>   for (var icon = 0, conj = codec.Conjugation[icon]; conj = codec.Conjugation[icon]; icon++) {
>     var res = 'xxx';
>     try {
>       res = codec.conjugateAuxiliary(v, iaux, icon).join(' / ');
>     } catch (e) {}
>     console.log(aux, conj, res);
>   }
> }
> ```
> 
> And searching the output of this, I see that `ShortenedCausative Ta 書かしだ`. I had a copy-paste bug in my code, and I didn't test す+past tense, so it wasn't caught 😿, but now it is fixed and a test added 😄!
> ## 2. Missing ば
> 
> About the ば at the end of the conditional—these are left off because in the book, Kamiya-sensei indicates the ば in parentheses, which she does when the conjugation is often used with something but not always:
> 
> ![kamiya](https://user-images.githubusercontent.com/37649/48680620-de185f00-eb6a-11e8-89ac-25f233f23920.jpg)
> 
> _**But**_ I checked all the examples of using the conditional in the book, and all of them have ば, sooo I'm ok with adding ば as a suffix when using `codec.Conjugation.Conditional`. This will take a bit more testing than I can do right now—I'm opening a branch for this and should have it done within 24 hours and will update this when that's done.
> ## 3. "no い"
> 
> My code snippet above produces `Tagaru Negative 書きたがら`, and this is related again to the fact that for たがる, on page 38, Kamiya-sensei gives `(ない)` in parentheses. This is also why, e.g., `Potential Negative 書け`, because while most usages of negatively-conjugated verbs have ない at the end, you can also build verbs like
> 
>     * "Vneg + reru/rareru" (page 123)
> 
>     * "Vneg + seru/saseru" (p. 128)
> 
>     * "Vneg + nakereba/nakattara" (p. 131)
> 
>     * etc.
> 
> 
> So for this case, I don't think it'd be safe to automatically add ない whenever conjugating a verb with codec.Conjugation.Negative.
> 
> Does this make sense?

For your last question of Negative form of a verb, well, if you are talking about negative form of Masu, it is ません,which has nothing to do with ない, but for all other negative plain form of verbs, ない is supposed to be added to the end.

**Comment by fasiha** [comment]
Your comment with the long code snippet is a bit hard to read—it's much easier to paste a diff, i.e., if you clone this repository, then make edits in it, `git diff > changes.diff` and paste the contents of the file here.

But, I do see your note about いらっしゃる's imperative. I included this because it's in the book: page 22 gives the 2nd and 4th (conjunctive and imperative) conjugations of いらっしゃる and I wanted to include that here.

Is there anything else in that code paste that you wanted me to see? (Looking at a diff makes this much easier!)

---

About ない, this is definitely confusing and not my favorite part of this library. Before diving into more explanation, consider the following output:
```js
codec.conjugateTypeI('書く', codec.Conjugation.Negative)      // [ '書か' ]
codec.conjugateTypeI('書きたがる', codec.Conjugation.Negative) // [ '書きたがら' ]
```
When you specify `codec.Conjugation.Negative` in this way, just the conjugation without the ない is returned, because of the reasons I mentioned before: negatively-conjugated verbs can be suffixed by several things, not just ない.

However, also consider:
```js
codec.conjugateAuxiliary('書く', codec.Auxiliary.Nai, codec.Conjugation.Negative) // [ '書かなくはない' ]
```
When I first saw this line in the book, I laughed. But of course, you have auxiliaries like ない and ます and ほしい etc., each of which can be conjugated as Negative, Conjunctive, Dictionary, etc.

The book is actually quite specific about this (it's always possible that it made a mistake, so I'm glad we're looking at this closely): for some auxiliaries conjugated as negative, i.e., `codec.conjugateAuxiliary('書く', codec.Auxiliary.Hoshii, codec.Conjugation.Negative) // [ '書いてほしくない' ]`, the book explicitly puts the ない at the end, like you suggested.

But for other auxiliaries, including たがる, which is a real godan verb, the negative conjugation is left *without* ない, because of the reason mentioned above. I'm not sure if a word like 書きたがらなくて, i.e., "かく + たがる + negative conjugation + なくて", would ever make sense, but it's conceivable according to the logic of the conjugation table, which is why the ない cannot be added automatically whenever codec.Conjugation.Negative is used.

So note that I wanted this project to become a deconjugator also, where if you gave the not-yet-written deconjugator a word like the above, it would be able to pull out all those pieces. One way I was thinking of writing this deconjugator was to basically do what you did here, run the conjugator for all auxiliaries and conjugations, and for that to work, I wanted codec.Conjugation.Negative to strictly stick to the actual conjugation rules.

For user apps, I am totally ok with appending ない whenever a user asks for a negative conjugation! But that would be a user-land app-level decision and wouldn't happen in this low-level library?

Let me know what you think, I'm super-happy at the attention you're giving this and would love to make it more ergonomic. I stopped working on this because I couldn't find a neat way to represent "verb + negative + ta (past tense)" in the conjugator. But it should still be useful for many other things.

**Comment by shilik** [comment]
I am not familiar with git ,but I will give it a try for editing the diff.
After that, let's check what needs to be done for the results.


Best

Shilik

**Comment by fasiha** [comment]
Ok, so what you can do is:
```
$ git clone https://github.com/fasiha/kamiya-codec.git
$ cd kamiya-codec
$ npm install
$ npm run build
```
This checks out this library as a git repo. What you were doing earlier, `npm install kamiya-codec`, was getting npm's copy of the library, which doesn't have git's metadata, and is really tough to experiment with. Editing code with a freshly-cloned copy of the repo is much better. After you make edits to the TypeScript `ts` files (or the JavaScript files, if you prefer), you can run `git diff` to see the differences.

What app are you making? I'd like to see it, because something I envisioned making with this library is an app that has all the various sentence formats that Kamiya-sensei's book had: an app where you could type in a verb, then select an auxiliary (optional), then select a conjugation, then see all the sentence patterns that could be built using those… I'm curious what others want to do with it.

**Comment by shilik** [comment]
Thanks for the direction, I will try it later.

I have developed a similar web-based system called Katsuyou (it is down
now, I can show you a snap shot of what it looks like when I return home)
which means learners can look up what a japanese word (verb,adjective,
noun) can be used in terms of forms.
Now I have turn my attention to mobile app development, so I am considering
the development of an app that can show possible forms of any japanese
words(or verbs), and integrate it into my collocation system to help
japanese learners know better how a japanese word can actually be used in
an authentic situation.
Here you can see many systems/apps I have developed so far.
https://www.youtube.com/channel/UCuoYEj3lSUFa9i9UcFtp7jQ?view_as=subscriber

shilik

**Comment by shilik** [comment]
I have follow your direction and modified the index.js file, then use git diff to see the changes.
So what is the next step to make these changes merge into your codes?

**Comment by fasiha** [comment]
> I have follow your direction and modified the index.js file, then use git diff to see the changes.
> So what is the next step to make these changes merge into your codes?

After making sure the diff only shows what's relevant (i.e., no whitespace changes, etc.), just copy and paste that diff into a comment here and we can discuss it further. (The more formal GitHub route is to use [Pull Requests](https://help.github.com/articles/about-pull-requests/) but working with diffs (and patches) is just as easy.)

**Comment by fasiha** [comment]
The latest versions of this library return conjugations ending in ば  and ます along with the naked forms 😄
